base_url = "https://zola.docs.saop.cc/"
title = "Zola"
description = "无需依赖，单一二进制文件的静态站点生成器。"
default_language = "zh"

compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
  { name = "theme-tags"}
]

[search]
index_format = "fuse_json"

[markdown]
external_links_class = "external"

[markdown.highlighting]
theme = "catppuccin-mocha"
#error_on_missing_language = true

[link_checker]
internal_level = "warn"

[extra]
author = "Vincent Prouillet"

[translations]
documentation = "文档"
themes = "主题"
guestbook = "留言板"
forum = "论坛"
github = "GitHub"
search_placeholder = "搜索文档"
title = "您的一站式静态站点引擎"
tagline = "告别依赖。所有功能尽在一个二进制文件中。"
get_started = "开始使用"
no_deps_title = "无依赖"
no_deps_desc = "Zola 是一个单一的可执行文件，内置了 Sass 编译、语法高亮、目录生成以及许多传统上需要设置开发环境或添加 JavaScript 库才能实现的功能。"
fast_title = "极速"
fast_desc = "平均每个站点的生成时间不到一秒，包括 Sass 编译和语法高亮。"
scalable_title = "可扩展"
scalable_desc = "Zola 将您的整个站点渲染为静态文件，这使得处理任何流量都变得轻而易举，而且无需担心管理服务器或数据库。"
easy_title = "易于使用"
easy_desc_1 = "从 CLI 到模板引擎，一切都设计得直观易用。别只听我说，看看"
easy_desc_link = "文档"
easy_desc_2 = "自己体验一下。"
flexible_title = "灵活"
flexible_desc = "Zola 不会妨碍您，让您可以专注于内容，无论是博客、知识库、落地页还是它们的组合。"
augmented_title = "增强的 Markdown"
augmented_desc_1 = "Zola 自带"
augmented_desc_link_1 = "shortcodes"
augmented_desc_2 = "和"
augmented_desc_link_2 = "内部链接"
augmented_desc_3 = "功能，让您更轻松地编写内容。"
total_visits = "本站总访问"
visits_count = "次，访客"
people = "人"
page_visits = "本页访问"
times = "次"

# English language configuration
[languages.en]
title = "Zola"
description = "A fast static site generator in a single binary with everything built-in."
generate_feeds = true
build_search_index = true
taxonomies = [
    {name = "theme-tags"}
]

[languages.en.translations]
documentation = "Documentation"
themes = "Themes"
guestbook = "Guestbook"
forum = "Forum"
github = "GitHub"
search_placeholder = "Search"
title = "Your one-stop static site engine"
tagline = "Forget dependencies. Everything you need in one binary."
get_started = "Get started"
no_deps_title = "No dependencies"
no_deps_desc = "Zola comes as a single executable with Sass compilation, syntax highlighting, table of contents and many other features that traditionally require setting up a dev environment or adding some JavaScript libraries."
fast_title = "Blazing fast"
fast_desc = "The average site is generated in less than a second, including Sass compilation and syntax highlighting."
scalable_title = "Scalable"
scalable_desc = "Zola renders your whole site as static files, making it trivial to handle any kind of traffic with no worries about managing a server or a database."
easy_title = "Easy to use"
easy_desc_1 = "From the CLI to the template engine, everything is designed to be intuitive. Don't take my word for it, check out the"
easy_desc_link = "documentation"
easy_desc_2 = "and see for yourself."
flexible_title = "Flexible"
flexible_desc = "Zola gets out of your way so you can focus on your content, be it a blog, a knowledge base, a landing page or a combination of them."
augmented_title = "Augmented Markdown"
augmented_desc_1 = "Zola comes with built-in support for"
augmented_desc_link_1 = "shortcodes"
augmented_desc_2 = "and"
augmented_desc_link_2 = "internal linking"
augmented_desc_3 = "to make writing content easier."
total_visits = "Total visits"
visits_count = "times, visitors"
people = "people"
page_visits = "Page visits"
times = "times"
