base_url = "https://zola.docs.saop.cc/"
title = "Zola"
description = "无需依赖，单一二进制文件的静态站点生成器。"
default_language = "zh"

compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
  { name = "theme-tags"}
]

[search]
index_format = "fuse_json"

[markdown]
external_links_class = "external"

[markdown.highlighting]
theme = "catppuccin-mocha"
#error_on_missing_language = true

[link_checker]
internal_level = "warn"

[extra]
author = "Vincent Prouillet"
