base_url = "https://zola.docs.saop.cc/"
title = "Zola"
description = "Zola 中文社区文档与汉化站，欢迎一起完善。"
default_language = "zh"

compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
  { name = "theme-tags"}
]

[search]
index_format = "fuse_json"

[markdown]
external_links_class = "external"
external_links_target_blank = true

[markdown.highlighting]
theme = "catppuccin-mocha"
#error_on_missing_language = true

[link_checker]
internal_level = "warn"

[extra]
author = "Vincent Prouillet"

[translations]
documentation = "文档"
themes = "主题"
guestbook = "留言板"
forum = "论坛"
github = "GitHub"
search = "搜索"
search_placeholder = "搜索文档"
title = "Zola 中文社区文档站"
tagline = "由社区共建的 Zola 中文文档与汉化内容。"
get_started = "开始使用"
no_deps_title = "无依赖"
no_deps_desc = "Zola 是一个单一的可执行文件，内置了 Sass 编译、语法高亮、目录生成以及许多传统上需要设置开发环境或添加 JavaScript 库才能实现的功能。"
fast_title = "极速"
fast_desc = "平均每个站点的生成时间不到一秒，包括 Sass 编译和语法高亮。"
scalable_title = "可扩展"
scalable_desc = "Zola 将您的整个站点渲染为静态文件，这使得处理任何流量都变得轻而易举，而且无需担心管理服务器或数据库。"
easy_title = "易于使用"
easy_desc_1 = "从 CLI 到模板引擎，一切都设计得直观易用。别只听我说，看看"
easy_desc_link = "文档"
easy_desc_2 = "自己体验一下。"
flexible_title = "灵活"
flexible_desc = "Zola 不会妨碍您，让您可以专注于内容，无论是博客、知识库、落地页还是它们的组合。"
augmented_title = "增强的 Markdown"
augmented_desc_1 = "Zola 自带"
augmented_desc_link_1 = "shortcodes"
augmented_desc_2 = "和"
augmented_desc_link_2 = "内部链接"
augmented_desc_3 = "功能，让您更轻松地编写内容。"
total_visits = "本站总访问"
visits_count = "次，访客"
people = "人"
page_visits = "本页访问"
times = "次"
ai_translated_notice = "本站中文内容由 AI 翻译。"
