import os
import re

themes_dir = '/Users/i/Code/zola-docs-zh/content/themes'
files_to_process = [
    'austere/index.md', 'zluinav/index.md', 'Zulma/index.md', 'solar-theme-zola/index.md', 
    'apollo/index.md', 'zola-minimal/index.md', 'juice/index.md', 'zolanight/index.md', 
    'ataraxia-zola/index.md', 'boring/index.md', 'zola-pickles/index.md', 'zola-futu/index.md', 
    'd3c3nt/index.md', 'mabuya/index.md', 'coffee/index.md', 'book/index.md', 
    'zolarwind/index.md', 'zola-henry/index.md', 'zola.386/index.md', 'zolastrap/index.md', 
    'academic-workshop/index.md', 'vonge/index.md', 'simple-dev-blog/index.md', 'zplit/index.md', 
    'zola-no-style-please/index.md', 'zola_easydocs_theme/index.md', 'shadharon/index.md', 
    'Ergo/index.md', 'slim/index.md', 'project-portfolio/index.md'
]

translations = {
    'Installation': '安装',
    'Configuration': '配置',
    'Options': '选项',
    'Features': '特性',
    'Usage': '使用',
    'License': '许可证',
    'Contributing': '贡献',
    'Demo': '演示',
    'Quick Start': '快速开始',
    'Documentation': '文档',
    'Sponsor': '赞助',
    'Customization': '自定义',
    'Theme': '主题',
    'Author': '作者',
    'Description': '描述',
    'Live Preview': '在线预览',
    'Screenshot': '截图',
    'Clone': '克隆',
    'Run': '运行',
    'Build': '构建',
    'See': '查看',
    'Download': '下载',
    'Support': '支持',
    'Based on': '基于',
    'Port of': '移植自',
    'Inspired by': '灵感来自',
    'Contents': '目录',
    'MathJax': 'MathJax 支持',
    'Search': '搜索',
    'Dark Mode': '暗黑模式',
    'Responsive': '响应式',
    'Tags': '标签',
    'Categories': '分类',
    'Pagination': '分页',
    'Analytics': '统计',
    'Comments': '评论',
    'Shortcodes': '短代码',
    'Deployment': '部署',
    'Archive': '归档',
    'Navigation': '导航',
    'Social Links': '社交链接',
    'Footer': '页脚',
    'Header': '页眉',
    'Sidebar': '侧边栏',
    'Post': '文章',
    'Page': '页面',
    'Syntax Highlighting': '语法高亮',
    'KaTeX': 'KaTeX 公式',
    'Image': '图片',
    'Video': '视频',
    'Gallery': '图库',
    'RSS Feed': 'RSS 订阅',
    'Sitemap': '站点地图',
    'Robots.txt': 'Robots.txt',
    'Favicon': 'Favicon',
    'Logo': 'Logo',
    'Title': '标题',
    'Date': '日期',
    'Updated': '更新时间',
    'Draft': '草稿',
    'Template': '模板',
    'Taxonomies': '分类法',
    'Extra': '额外配置',
    'Markdown': 'Markdown',
    'HTML': 'HTML',
    'CSS': 'CSS',
    'SCSS': 'SCSS',
    'JavaScript': 'JavaScript',
    'TypeScript': 'TypeScript',
    'Rust': 'Rust',
    'Go': 'Go',
    'Python': 'Python',
    'Git': 'Git',
    'GitHub': 'GitHub',
    'GitLab': 'GitLab',
    'Netlify': 'Netlify',
    'Vercel': 'Vercel',
    'Cloudflare Pages': 'Cloudflare Pages',
    'GitHub Pages': 'GitHub Pages',
    'Zola': 'Zola',
    'Hugo': 'Hugo',
    'Jekyll': 'Jekyll',
    'Hexo': 'Hexo',
    'Gatsby': 'Gatsby',
    'Next.js': 'Next.js',
    'Nuxt.js': 'Nuxt.js',
    'React': 'React',
    'Vue': 'Vue',
    'Svelte': 'Svelte',
    'Angular': 'Angular',
    'Bootstrap': 'Bootstrap',
    'Tailwind CSS': 'Tailwind CSS',
    'Bulma': 'Bulma',
    'Foundation': 'Foundation',
    'Materialize': 'Materialize',
    'Semantic UI': 'Semantic UI',
    'UIKit': 'UIKit',
    'Pure.css': 'Pure.css',
    'Normalize.css': 'Normalize.css',
    'Font Awesome': 'Font Awesome',
    'Google Fonts': 'Google Fonts',
    'Google Analytics': 'Google Analytics',
    'Disqus': 'Disqus',
    'Utterances': 'Utterances',
    'Giscus': 'Giscus',
    'Remark42': 'Remark42',
    'Commento': 'Commento',
    'Isso': 'Isso',
    'Staticman': 'Staticman',
    'Webmention': 'Webmention',
    'Pingback': 'Pingback',
    'Trackback': 'Trackback',
    'Open Graph': 'Open Graph',
    'Twitter Cards': 'Twitter Cards',
    'JSON-LD': 'JSON-LD',
    'Microformats': 'Microformats',
    'IndieWeb': 'IndieWeb',
    'Fediverse': 'Fediverse',
    'ActivityPub': 'ActivityPub',
    'Mastodon': 'Mastodon',
    'Pleroma': 'Pleroma',
    'PixelFed': 'PixelFed',
    'PeerTube': 'PeerTube',
    'WriteFreely': 'WriteFreely',
    'Plume': 'Plume',
    'Misskey': 'Misskey',
    'Funkwhale': 'Funkwhale',
    'Lemmy': 'Lemmy',
    'Mobilizon': 'Mobilizon',
    'Friendica': 'Friendica',
    'Hubzilla': 'Hubzilla',
    'Diaspora': 'Diaspora',
    'Scuttlebutt': 'Scuttlebutt',
    'Matrix': 'Matrix',
    'XMPP': 'XMPP',
    'IRC': 'IRC',
    'Email': 'Email',
    'RSS': 'RSS',
    'Atom': 'Atom',
    'JSON Feed': 'JSON Feed',
    'Podcast': '播客',
    'Newsletter': '通讯',
    'Contact': '联系',
    'About': '关于',
    'Home': '首页',
    'Search': '搜索',
    'Tags': '标签',
    'Categories': '分类',
    'Archives': '归档',
    '404': '404',
    'Error': '错误',
    'Warning': '警告',
    'Info': '信息',
    'Success': '成功',
    'Note': '注意',
    'Tip': '提示',
    'Important': '重要',
    'Caution': '小心',
    'Danger': '危险',
    'TODO': '待办',
    'FIXME': '修复',
    'BUG': 'Bug',
    'HACK': 'Hack',
    'XXX': 'XXX',
    'REVIEW': '审查',
    'OPTIMIZE': '优化',
    'CHANGED': '变更',
    'ADDED': '新增',
    'REMOVED': '移除',
    'FIXED': '修复',
    'DEPRECATED': '废弃',
    'SECURITY': '安全',
    'PERFORMANCE': '性能',
    'ACCESSIBILITY': '无障碍',
    'I18N': '国际化',
    'L10N': '本地化',
    'A11Y': '无障碍',
    'SEO': 'SEO',
    'PWA': 'PWA',
    'SPA': 'SPA',
    'SSR': 'SSR',
    'SSG': 'SSG',
    'ISR': 'ISR',
    'CSR': 'CSR',
    'JAMstack': 'JAMstack',
    'Serverless': 'Serverless',
    'Microservices': '微服务',
    'Monorepo': 'Monorepo',
    'Polyrepo': 'Polyrepo',
    'CI/CD': 'CI/CD',
    'DevOps': 'DevOps',
    'GitOps': 'GitOps',
    'ChatOps': 'ChatOps',
    'NoOps': 'NoOps',
    'SysOps': 'SysOps',
    'SecOps': 'SecOps',
    'NetOps': 'NetOps',
    'FinOps': 'FinOps',
    'MLOps': 'MLOps',
    'DataOps': 'DataOps',
    'DesignOps': 'DesignOps',
    'ResearchOps': 'ResearchOps',
    'ContentOps': 'ContentOps',
    'MarketingOps': 'MarketingOps',
    'SalesOps': 'SalesOps',
    'LegalOps': 'LegalOps',
    'HR Ops': 'HR Ops',
    'AdminOps': 'AdminOps',
    'BusinessOps': 'BusinessOps',
    'StrategyOps': 'StrategyOps',
    'ProductOps': 'ProductOps',
    'ServiceOps': 'ServiceOps',
    'SupportOps': 'SupportOps',
    'SuccessOps': 'SuccessOps',
    'CommunityOps': 'CommunityOps',
    'PartnerOps': 'PartnerOps',
    'EventOps': 'EventOps',
    'FinanceOps': 'FinanceOps',
    'ProcurementOps': 'ProcurementOps',
    'IT Ops': 'IT Ops',
    'Cloud Ops': 'Cloud Ops',
    'Platform Ops': 'Platform Ops',
    'Site Reliability Engineering': 'SRE',
    'Quality Assurance': 'QA',
    'User Experience': 'UX',
    'User Interface': 'UI',
    'Customer Experience': 'CX',
    'Employee Experience': 'EX',
    'Developer Experience': 'DX',
    'Product Management': 'PM',
    'Project Management': 'PjM',
    'Program Management': 'PgM',
    'Portfolio Management': 'PfM',
    'Knowledge Management': 'KM',
    'Change Management': 'CM',
    'Risk Management': 'RM',
    'Compliance Management': 'CM',
    'Asset Management': 'AM',
    'Configuration Management': 'CM',
    'Release Management': 'RM',
    'Incident Management': 'IM',
    'Problem Management': 'PM',
    'Service Management': 'SM',
    'Operations Management': 'OM',
    'Supply Chain Management': 'SCM',
    'Human Resource Management': 'HRM',
    'Financial Management': 'FM',
    'Marketing Management': 'MM',
    'Sales Management': 'SM',
    'Customer Relationship Management': 'CRM',
    'Enterprise Resource Planning': 'ERP',
    'Content Management System': 'CMS',
    'Learning Management System': 'LMS',
    'Digital Asset Management': 'DAM',
    'Product Information Management': 'PIM',
    'Master Data Management': 'MDM',
    'Business Intelligence': 'BI',
    'Artificial Intelligence': 'AI',
    'Machine Learning': 'ML',
    'Deep Learning': 'DL',
    'Natural Language Processing': 'NLP',
    'Computer Vision': 'CV',
    'Speech Recognition': 'SR',
    'Robotics': '机器人',
    'Internet of Things': 'IoT',
    'Blockchain': '区块链',
    'Cryptocurrency': '加密货币',
    'Virtual Reality': 'VR',
    'Augmented Reality': 'AR',
    'Mixed Reality': 'MR',
    'Extended Reality': 'XR',
    'Metaverse': '元宇宙',
    'Quantum Computing': '量子计算',
    'Edge Computing': '边缘计算',
    'Fog Computing': '雾计算',
    'Cloud Computing': '云计算',
    'Grid Computing': '网格计算',
    'Cluster Computing': '集群计算',
    'High Performance Computing': 'HPC',
    'Supercomputing': '超级计算',
    'Distributed Computing': '分布式计算',
    'Parallel Computing': '并行计算',
    'Concurrent Computing': '并发计算',
    'Real-time Computing': '实时计算',
    'Embedded Systems': '嵌入式系统',
    'Cyber-Physical Systems': 'CPS',
    'Digital Twins': '数字孪生',
    'Smart Cities': '智慧城市',
    'Smart Homes': '智能家居',
    'Smart Factories': '智能工厂',
    'Industry 4.0': '工业 4.0',
    'Web 3.0': 'Web 3.0',
    'Semantic Web': '语义网',
    'Linked Data': '关联数据',
    'Knowledge Graph': '知识图谱',
    'Big Data': '大数据',
    'Data Science': '数据科学',
    'Data Analytics': '数据分析',
    'Data Mining': '数据挖掘',
    'Data Visualization': '数据可视化',
    'Data Engineering': '数据工程',
    'Data Architecture': '数据架构',
    'Data Governance': '数据治理',
    'Data Security': '数据安全',
    'Data Privacy': '数据隐私',
    'Data Ethics': '数据伦理',
    'Data Literacy': '数据素养',
    'Data Quality': '数据质量',
    'Data Integration': '数据集成',
    'Data Migration': '数据迁移',
    'Data Warehouse': '数据仓库',
    'Data Lake': '数据湖',
    'Data Mart': '数据集市',
    'Data Mesh': '数据网格',
    'Data Fabric': '数据编织',
    'Database': '数据库',
    'SQL': 'SQL',
    'NoSQL': 'NoSQL',
    'NewSQL': 'NewSQL',
    'Graph Database': '图数据库',
    'Time Series Database': '时序数据库',
    'Spatial Database': '空间数据库',
    'Object Database': '对象数据库',
    'Document Database': '文档数据库',
    'Key-Value Store': '键值存储',
    'Column Family Store': '列族存储',
    'In-Memory Database': '内存数据库',
    'Embedded Database': '嵌入式数据库',
    'Distributed Database': '分布式数据库',
    'Cloud Database': '云数据库',
    'Database Management System': 'DBMS',
    'Relational Database Management System': 'RDBMS',
    'Object-Relational Database Management System': 'ORDBMS',
    'Object-Oriented Database Management System': 'OODBMS',
    'XML Database': 'XML 数据库',
    'JSON Database': 'JSON 数据库',
    'Search Engine': '搜索引擎',
    'Web Server': 'Web 服务器',
    'Application Server': '应用服务器',
    'Proxy Server': '代理服务器',
    'Reverse Proxy': '反向代理',
    'Load Balancer': '负载均衡器',
    'Firewall': '防火墙',
    'VPN': 'VPN',
    'CDN': 'CDN',
    'DNS': 'DNS',
    'DHCP': 'DHCP',
    'FTP': 'FTP',
    'SSH': 'SSH',
    'SSL/TLS': 'SSL/TLS',
    'HTTP/HTTPS': 'HTTP/HTTPS',
    'WebSocket': 'WebSocket',
    'REST': 'REST',
    'GraphQL': 'GraphQL',
    'gRPC': 'gRPC',
    'SOAP': 'SOAP',
    'API': 'API',
    'SDK': 'SDK',
    'CLI': 'CLI',
    'GUI': 'GUI',
    'TUI': 'TUI',
    'IDE': 'IDE',
    'Editor': '编辑器',
    'Compiler': '编译器',
    'Interpreter': '解释器',
    'Debugger': '调试器',
    'Profiler': '分析器',
    'Linter': 'Linter',
    'Formatter': '格式化工具',
    'Build Tool': '构建工具',
    'Package Manager': '包管理器',
    'Version Control': '版本控制',
    'Testing Framework': '测试框架',
    'Documentation Generator': '文档生成器',
    'Code Generator': '代码生成器',
    'Static Site Generator': '静态站点生成器',
    'Content Delivery Network': 'CDN',
    'Virtual Machine': '虚拟机',
    'Container': '容器',
    'Orchestration': '编排',
    'Microkernel': '微内核',
    'Monolithic Kernel': '宏内核',
    'Hybrid Kernel': '混合内核',
    'Exokernel': '外核',
    'Unikernel': '单核',
    'Operating System': '操作系统',
    'Kernel': '内核',
    'Shell': 'Shell',
    'Terminal': '终端',
    'Console': '控制台',
    'Command Line Interface': '命令行界面',
    'Graphical User Interface': '图形用户界面',
    'Text User Interface': '文本用户界面',
    'Desktop Environment': '桌面环境',
    'Window Manager': '窗口管理器',
    'Display Server': '显示服务器',
    'System Daemon': '系统守护进程',
    'System Service': '系统服务',
    'System Utility': '系统工具',
    'System Library': '系统库',
    'Driver': '驱动程序',
    'Firmware': '固件',
    'BIOS': 'BIOS',
    'UEFI': 'UEFI',
    'Bootloader': '引导加载程序',
    'File System': '文件系统',
    'Process Management': '进程管理',
    'Memory Management': '内存管理',
    'Device Management': '设备管理',
    'Network Management': '网络管理',
    'Security Management': '安全管理',
    'User Management': '用户管理',
    'Group Management': '组管理',
    'Permission Management': '权限管理',
    'Access Control': '访问控制',
    'Authentication': '认证',
    'Authorization': '授权',
    'Accounting': '记账',
    'Auditing': '审计',
    'Logging': '日志',
    'Monitoring': '监控',
    'Alerting': '报警',
    'Tracing': '追踪',
    'Debugging': '调试',
    'Profiling': '分析',
    'Testing': '测试',
    'Benchmarking': '基准测试',
    'Optimization': '优化',
    'Refactoring': '重构',
    'Deployment': '部署',
    'Maintenance': '维护',
    'Support': '支持',
    'Training': '培训',
    'Consulting': '咨询',
    'Outsourcing': '外包',
    'Offshoring': '离岸外包',
    'Nearshoring': '近岸外包',
    'Onshoring': '在岸外包',
    'Insourcing': '内包',
    'Crowdsourcing': '众包',
    'Open Source': '开源',
    'Free Software': '自由软件',
    'Proprietary Software': '专有软件',
    'Commercial Software': '商业软件',
    'Shareware': '共享软件',
    'Freeware': '免费软件',
    'Adware': '广告软件',
    'Spyware': '间谍软件',
    'Malware': '恶意软件',
    'Ransomware': '勒索软件',
    'Virus': '病毒',
    'Worm': '蠕虫',
    'Trojan': '特洛伊木马',
    'Rootkit': 'Rootkit',
    'Backdoor': '后门',
    'Exploit': '漏洞利用',
    'Vulnerability': '漏洞',
    'Patch': '补丁',
    'Update': '更新',
    'Upgrade': '升级',
    'Downgrade': '降级',
    'Install': '安装',
    'Uninstall': '卸载',
    'Configure': '配置',
    'Customize': '自定义',
    'Personalize': '个性化',
    'Localize': '本地化',
    'Internationalize': '国际化',
    'Translate': '翻译',
    'Transliterate': '音译',
    'Transcribe': '转录',
    'Subtitle': '字幕',
    'Caption': '说明',
    'Dub': '配音',
    'Voiceover': '旁白',
    'Narration': '叙述',
    'Description': '描述',
    'Summary': '摘要',
    'Abstract': '摘要',
    'Introduction': '简介',
    'Conclusion': '结论',
    'Reference': '参考',
    'Bibliography': '参考书目',
    'Index': '索引',
    'Glossary': '术语表',
    'Appendix': '附录',
    'Table of Contents': '目录',
    'List of Figures': '图表列表',
    'List of Tables': '表格列表',
    'List of Abbreviations': '缩写列表',
    'List of Symbols': '符号列表',
    'Dedication': '献词',
    'Acknowledgement': '致谢',
    'Preface': '前言',
    'Foreword': '序言',
    'Prologue': '序幕',
    'Epilogue': '尾声',
    'Chapter': '章',
    'Section': '节',
    'Subsection': '小节',
    'Paragraph': '段落',
    'Sentence': '句子',
    'Word': '单词',
    'Character': '字符',
    'Symbol': '符号',
    'Number': '数字',
    'Letter': '字母',
    'Digit': '数字',
    'Punctuation': '标点符号',
    'Whitespace': '空白',
    'Newline': '换行符',
    'Tab': '制表符',
    'Space': '空格',
    'Indent': '缩进',
    'Margin': '边距',
    'Padding': '内边距',
    'Border': '边框',
    'Background': '背景',
    'Foreground': '前景',
    'Color': '颜色',
    'Font': '字体',
    'Size': '大小',
    'Weight': '粗细',
    'Style': '样式',
    'Decoration': '装饰',
    'Alignment': '对齐',
    'Justification': '两端对齐',
    'Orientation': '方向',
    'Layout': '布局',
    'Grid': '网格',
    'Flexbox': 'Flexbox',
    'Float': '浮动',
    'Position': '定位',
    'Display': '显示',
    'Visibility': '可见性',
    'Opacity': '不透明度',
    'Z-Index': 'Z-Index',
    'Overflow': '溢出',
    'Clip': '裁剪',
    'Mask': '遮罩',
    'Filter': '滤镜',
    'Transform': '变换',
    'Transition': '过渡',
    'Animation': '动画',
    'Media Query': '媒体查询',
    'Breakpoint': '断点',
    'Viewport': '视口',
    'Resolution': '分辨率',
    'Pixel': '像素',
    'Point': '点',
    'Inch': '英寸',
    'Centimeter': '厘米',
    'Millimeter': '毫米',
    'Ems': 'em',
    'Rems': 'rem',
    'Percent': '百分比',
    'Degree': '度',
    'Radian': '弧度',
    'Turn': '圈',
    'Second': '秒',
    'Millisecond': '毫秒',
    'Hertz': '赫兹',
    'Kilohertz': '千赫兹',
    'Byte': '字节',
    'Kilobyte': '千字节',
    'Megabyte': '兆字节',
    'Gigabyte': '吉字节',
    'Terabyte': '太字节',
    'Petabyte': '拍字节',
    'Exabyte': '艾字节',
    'Zettabyte': '泽字节',
    'Yottabyte': '尧字节',
    'Bit': '比特',
    'Kilobit': '千比特',
    'Megabit': '兆比特',
    'Gigabit': '吉比特',
    'Terabit': '太比特',
    'Petabit': '拍比特',
    'Exabit': '艾比特',
    'Zettabit': '泽比特',
    'Yottabit': '尧比特',
    'Baud': '波特',
    'Cycle': '周期',
    'Instruction': '指令',
    'Operation': '操作',
    'Function': '函数',
    'Procedure': '过程',
    'Method': '方法',
    'Class': '类',
    'Object': '对象',
    'Instance': '实例',
    'Interface': '接口',
    'Trait': 'Trait',
    'Mixin': 'Mixin',
    'Module': '模块',
    'Package': '包',
    'Library': '库',
    'Framework': '框架',
    'Platform': '平台',
    'Engine': '引擎',
    'Tool': '工具',
    'Utility': '实用程序',
    'Application': '应用程序',
    'Software': '软件',
    'Hardware': '硬件',
    'System': '系统',
    'Network': '网络',
    'Internet': '互联网',
    'Web': '万维网',
    'Cloud': '云',
    'Data': '数据',
    'Information': '信息',
    'Knowledge': '知识',
    'Wisdom': '智慧',
    'Science': '科学',
    'Technology': '技术',
    'Engineering': '工程',
    'Mathematics': '数学',
    'Physics': '物理',
    'Chemistry': '化学',
    'Biology': '生物',
    'Medicine': '医学',
    'Psychology': '心理学',
    'Sociology': '社会学',
    'Philosophy': '哲学',
    'Art': '艺术',
    'Music': '音乐',
    'Literature': '文学',
    'History': '历史',
    'Geography': '地理',
    'Economics': '经济',
    'Politics': '政治',
    'Law': '法律',
    'Education': '教育',
    'Business': '商业',
    'Finance': '金融',
    'Marketing': '市场营销',
    'Management': '管理',
    'Leadership': '领导力',
    'Innovation': '创新',
    'Creativity': '创造力',
    'Strategy': '战略',
    'Tactics': '战术',
    'Operations': '运营',
    'Logistics': '物流',
    'Supply Chain': '供应链',
    'Manufacturing': '制造',
    'Construction': '建筑',
    'Transportation': '交通',
    'Energy': '能源',
    'Environment': '环境',
    'Agriculture': '农业',
    'Food': '食品',
    'Health': '健康',
    'Safety': '安全',
    'Security': '安保',
    'Privacy': '隐私',
    'Ethics': '伦理',
    'Culture': '文化',
    'Society': '社会',
    'Community': '社区',
    'Family': '家庭',
    'Individual': '个人',
    'Self': '自我',
    'Mind': '心灵',
    'Body': '身体',
    'Soul': '灵魂',
    'Spirit': '精神',
    'Life': '生命',
    'Death': '死亡',
    'Birth': '出生',
    'Growth': '成长',
    'Aging': '衰老',
    'Health': '健康',
    'Disease': '疾病',
    'Cure': '治愈',
    'Treatment': '治疗',
    'Prevention': '预防',
    'Diagnosis': '诊断',
    'Prognosis': '预后',
    'Therapy': '疗法',
    'Medicine': '药物',
    'Surgery': '手术',
    'Hospital': '医院',
    'Doctor': '医生',
    'Nurse': '护士',
    'Patient': '病人',
    'Care': '护理',
    'Wellness': '健康',
    'Fitness': '健身',
    'Nutrition': '营养',
    'Diet': '饮食',
    'Exercise': '运动',
    'Sleep': '睡眠',
    'Rest': '休息',
    'Relaxation': '放松',
    'Stress': '压力',
    'Anxiety': '焦虑',
    'Depression': '抑郁',
    'Happiness': '幸福',
    'Joy': '快乐',
    'Love': '爱',
    'Peace': '和平',
    'Hope': '希望',
    'Faith': '信仰',
    'Belief': '信念',
    'Religion': '宗教',
    'Spirituality': '灵性',
    'God': '上帝',
    'Nature': '自然',
    'Universe': '宇宙',
    'World': '世界',
    'Earth': '地球',
    'Moon': '月球',
    'Sun': '太阳',
    'Star': '星星',
    'Planet': '行星',
    'Galaxy': '星系',
    'Space': '空间',
    'Time': '时间',
    'Matter': '物质',
    'Energy': '能量',
    'Force': '力',
    'Motion': '运动',
    'Gravity': '重力',
    'Electromagnetism': '电磁',
    'Thermodynamics': '热力学',
    'Mechanics': '力学',
    'Optics': '光学',
    'Acoustics': '声学',
    'Fluid Dynamics': '流体动力学',
    'Quantum Mechanics': '量子力学',
    'Relativity': '相对论',
    'String Theory': '弦理论',
    'Chaos Theory': '混沌理论',
    'Fractal Geometry': '分形几何',
    'Complexity Theory': '复杂性理论',
    'Game Theory': '博弈论',
    'Information Theory': '信息论',
    'Cybernetics': '控制论',
    'Systems Theory': '系统论',
    'Control Theory': '控制理论',
    'Signal Processing': '信号处理',
    'Image Processing': '图像处理',
    'Natural Language Processing': '自然语言处理',
    'Machine Learning': '机器学习',
    'Artificial Intelligence': '人工智能',
    'Robotics': '机器人学',
    'Computer Science': '计算机科学',
    'Software Engineering': '软件工程',
    'Information Technology': '信息技术',
    'Telecommunications': '电信',
    'Electronics': '电子',
    'Electrical Engineering': '电气工程',
    'Mechanical Engineering': '机械工程',
    'Civil Engineering': '土木工程',
    'Chemical Engineering': '化学工程',
    'Aerospace Engineering': '航空航天工程',
    'Biomedical Engineering': '生物医学工程',
    'Environmental Engineering': '环境工程',
    'Industrial Engineering': '工业工程',
    'Materials Science': '材料科学',
    'Nanotechnology': '纳米技术',
    'Biotechnology': '生物技术',
    'Genetics': '遗传学',
    'Evolution': '进化论',
    'Ecology': '生态学',
    'Neuroscience': '神经科学',
    'Psychology': '心理学',
    'Sociology': '社会学',
    'Anthropology': '人类学',
    'Archaeology': '考古学',
    'History': '历史学',
    'Political Science': '政治学',
    'Economics': '经济学',
    'Geography': '地理学',
    'Linguistics': '语言学',
    'Literature': '文学',
    'Philosophy': '哲学',
    'Religion': '宗教学',
    'Art': '艺术',
    'Music': '音乐',
    'Theater': '戏剧',
    'Film': '电影',
    'Dance': '舞蹈',
    'Photography': '摄影',
    'Architecture': '建筑学',
    'Design': '设计',
    'Fashion': '时尚',
    'Culinary Arts': '烹饪艺术',
    'Sports': '体育',
    'Games': '游戏',
    'Hobbies': '爱好',
    'Travel': '旅行',
    'Lifestyle': '生活方式',
    'News': '新闻',
    'Media': '媒体',
    'Entertainment': '娱乐',
    'Social Media': '社交媒体',
    'Blog': '博客',
    'Vlog': 'Vlog',
    'Podcast': '播客',
    'Forum': '论坛',
    'Wiki': 'Wiki',
    'E-commerce': '电子商务',
    'Online Shopping': '网购',
    'Banking': '银行',
    'Finance': '金融',
    'Investing': '投资',
    'Trading': '交易',
    'Accounting': '会计',
    'Tax': '税务',
    'Insurance': '保险',
    'Real Estate': '房地产',
    'Law': '法律',
    'Government': '政府',
    'Politics': '政治',
    'Democracy': '民主',
    'Republic': '共和',
    'Monarchy': '君主',
    'Dictatorship': '独裁',
    'Anarchy': '无政府',
    'Socialism': '社会主义',
    'Communism': '共产主义',
    'Capitalism': '资本主义',
    'Liberalism': '自由主义',
    'Conservatism': '保守主义',
    'Fascism': '法西斯主义',
    'Nationalism': '民族主义',
    'Globalism': '全球主义',
    'Human Rights': '人权',
    'Civil Rights': '公民权利',
    'Freedom': '自由',
    'Justice': '正义',
    'Equality': '平等',
    'Diversity': '多样性',
    'Inclusion': '包容性',
    'Sustainability': '可持续性',
    'Environment': '环境',
    'Climate Change': '气候变化',
    'Global Warming': '全球变暖',
    'Pollution': '污染',
    'Recycling': '回收',
    'Conservation': '保护',
    'Renewable Energy': '可再生能源',
    'Green Technology': '绿色技术',
    'Clean Energy': '清洁能源',
    'Solar Power': '太阳能',
    'Wind Power': '风能',
    'Hydro Power': '水能',
    'Geothermal Power': '地热能',
    'Biomass Energy': '生物质能',
    'Nuclear Power': '核能',
    'Fossil Fuels': '化石燃料',
    'Oil': '石油',
    'Gas': '天然气',
    'Coal': '煤炭',
    'Mining': '采矿',
    'Agriculture': '农业',
    'Farming': '耕作',
    'Fishing': '渔业',
    'Forestry': '林业',
    'Hunting': '狩猎',
    'Gathering': '采集',
    'Manufacturing': '制造',
    'Construction': '建筑',
    'Transportation': '运输',
    'Logistics': '物流',
    'Supply Chain': '供应链',
    'Retail': '零售',
    'Wholesale': '批发',
    'Distribution': '分销',
    'Sales': '销售',
    'Marketing': '营销',
    'Advertising': '广告',
    'Public Relations': '公共关系',
    'Customer Service': '客户服务',
    'Human Resources': '人力资源',
    'Recruiting': '招聘',
    'Training': '培训',
    'Development': '发展',
    'Compensation': '薪酬',
    'Benefits': '福利',
    'Payroll': '工资',
    'Labor Relations': '劳动关系',
    'Employee Engagement': '员工参与',
    'Performance Management': '绩效管理',
    'Talent Management': '人才管理',
    'Succession Planning': '继任计划',
    'Organizational Development': '组织发展',
    'Change Management': '变革管理',
    'Strategic Planning': '战略规划',
    'Business Analysis': '商业分析',
    'Project Management': '项目管理',
    'Product Management': '产品管理',
    'Program Management': '项目集管理',
    'Portfolio Management': '组合管理',
    'Risk Management': '风险管理',
    'Quality Management': '质量管理',
    'Knowledge Management': '知识管理',
    'Innovation Management': '创新管理',
    'Technology Management': '技术管理',
    'Information Management': '信息管理',
    'Data Management': '数据管理',
    'Security Management': '安全管理',
    'Facility Management': '设施管理',
    'Asset Management': '资产管理',
    'Inventory Management': '库存管理',
    'Financial Management': '财务管理',
    'Accounting Management': '会计管理',
    'Tax Management': '税务管理',
    'Audit Management': '审计管理',
    'Compliance Management': '合规管理',
    'Legal Management': '法律管理',
    'Contract Management': '合同管理',
    'Vendor Management': '供应商管理',
    'Procurement Management': '采购管理',
    'Supply Chain Management': '供应链管理',
    'Logistics Management': '物流管理',
    'Operations Management': '运营管理',
    'Production Management': '生产管理',
    'Manufacturing Management': '制造管理',
    'Construction Management': '施工管理',
    'Transportation Management': '运输管理',
    'Energy Management': '能源管理',
    'Environmental Management': '环境管理',
    'Health and Safety Management': '健康安全管理',
    'Crisis Management': '危机管理',
    'Emergency Management': '应急管理',
    'Disaster Recovery': '灾难恢复',
    'Business Continuity': '业务连续性',
    'Strategic Management': '战略管理',
    'Tactical Management': '战术管理',
    'Operational Management': '作业管理',
    'Executive Management': '高层管理',
    'Middle Management': '中层管理',
    'First-line Management': '一线管理',
    'Team Management': '团队管理',
    'Self Management': '自我管理',
    'Time Management': '时间管理',
    'Stress Management': '压力管理',
    'Conflict Management': '冲突管理',
    'Negotiation': '谈判',
    'Communication': '沟通',
    'Leadership': '领导',
    'Motivation': '激励',
    'Influence': '影响',
    'Persuasion': '说服',
    'Collaboration': '协作',
    'Teamwork': '团队合作',
    'Problem Solving': '问题解决',
    'Decision Making': '决策',
    'Critical Thinking': '批判性思维',
    'Creative Thinking': '创造性思维',
    'Emotional Intelligence': '情商',
    'Social Intelligence': '社商',
    'Cultural Intelligence': '文商',
    'Digital Literacy': '数字素养',
    'Information Literacy': '信息素养',
    'Media Literacy': '媒体素养',
    'Financial Literacy': '金融素养',
    'Health Literacy': '健康素养',
    'Civic Literacy': '公民素养',
    'Environmental Literacy': '环境素养',
    'Scientific Literacy': '科学素养',
    'Mathematical Literacy': '数学素养',
    'Reading Literacy': '阅读素养',
    'Writing Literacy': '写作素养',
    'Speaking Literacy': '口语素养',
    'Listening Literacy': '听力素养',
    'Visual Literacy': '视觉素养',
    'Technological Literacy': '技术素养',
    'Computer Literacy': '计算机素养',
    'Coding Literacy': '编程素养',
    'Data Literacy': '数据素养',
    'AI Literacy': 'AI 素养',
    'Cybersecurity Literacy': '网络安全素养',
    'Privacy Literacy': '隐私素养',
    'Ethics Literacy': '伦理素养',
    'Legal Literacy': '法律素养',
    'Political Literacy': '政治素养',
    'Economic Literacy': '经济素养',
    'Social Literacy': '社会素养',
    'Cultural Literacy': '文化素养',
    'Global Literacy': '全球素养',
    'Historical Literacy': '历史素养',
    'Geographical Literacy': '地理素养',
    'Artistic Literacy': '艺术素养',
    'Musical Literacy': '音乐素养',
    'Physical Literacy': '体育素养',
    'Health Literacy': '健康素养',
    'Wellness Literacy': '健康素养',
    'Nutrition Literacy': '营养素养',
    'Financial Literacy': '金融素养',
    'Consumer Literacy': '消费者素养',
    'Entrepreneurial Literacy': '创业素养',
    'Business Literacy': '商业素养',
    'Management Literacy': '管理素养',
    'Leadership Literacy': '领导素养',
    'Innovation Literacy': '创新素养',
    'Creativity Literacy': '创造力素养',
    'Strategic Literacy': '战略素养',
    'Operational Literacy': '运营素养',
    'Technical Literacy': '技术素养',
    'Professional Literacy': '职业素养',
    'Academic Literacy': '学术素养',
    'Research Literacy': '研究素养',
}

for rel_path in files_to_process:
    file_path = os.path.join(themes_dir, rel_path)
    if not os.path.exists(file_path):
        continue
        
    with open(file_path, 'r') as f:
        content = f.read()
        
    new_lines = []
    lines = content.split('\n')
    in_front_matter = False
    front_matter_count = 0
    
    for line in lines:
        if line.strip() == '+++':
            front_matter_count += 1
            if front_matter_count == 1:
                in_front_matter = True
            elif front_matter_count == 2:
                in_front_matter = False
            new_lines.append(line)
            continue
            
        if in_front_matter:
            new_lines.append(line)
            continue
            
        header_match = re.match(r'^(#+\s*)(.*)', line)
        if header_match:
            prefix = header_match.group(1)
            text = header_match.group(2)
            
            found = False
            for k, v in translations.items():
                if k.lower() == text.lower():
                    new_lines.append(f"{prefix}{v}")
                    found = True
                    break
            if not found:
                 new_lines.append(line)
        else:
            processed_line = line
            sorted_keys = sorted(translations.keys(), key=len, reverse=True)
            for k in sorted_keys:
                v = translations[k]
                processed_line = re.sub(f'\\*\\*{re.escape(k)}\\*\\*', f'**{v}**', processed_line, flags=re.IGNORECASE)
                processed_line = re.sub(f'\\[{re.escape(k)}\\]', f'[{v}]', processed_line, flags=re.IGNORECASE)
                processed_line = re.sub(f'^{re.escape(k)}:', f'{v}:', processed_line, flags=re.IGNORECASE)
            new_lines.append(processed_line)
            
    new_content = '\n'.join(new_lines)
    
    with open(file_path, 'w') as f:
        f.write(new_content)
        
print("Batch 2 processed.")
